steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: CreateEnv
    args: ['run', 'create-env']
    env:
      - BUN_ENV=${_BUN_ENV}
      - ALCHEMY_API_KEY=${_ALCHEMY_API_KEY}
      - INFURA_API_KEY=${_INFURA_API_KEY}
      - MONGO_URI=${_MONGO_URI}
      - PINATA_JWT=${_PINATA_JWT}
      - ICP_CANISTER_ID=${_ICP_CANISTER_ID}
      - ICP_MNEMONIC=${_ICP_MNEMONIC}
      - BOT_API_URL=${_BOT_API_URL}
      - BOT_DATA_TOKEN=${_BOT_DATA_TOKEN}
      - NFT_UPLOAD_IMAGE_ICP=${_NFT_UPLOAD_IMAGE_ICP}
      - NFT_UPLOAD_IMAGE_IPFS=${_NFT_UPLOAD_IMAGE_IPFS}
      - GCP_BUCKET_BASE_URL=${_GCP_BUCKET_BASE_URL}
      - PUSH_NETWORK=${_PUSH_NETWORK}
      - PUSH_ENVIRONMENT=${_PUSH_ENVIRONMENT}
      - PUSH_CHANNEL_ADDRESS=${_PUSH_CHANNEL_ADDRESS}
      - PUSH_CHANNEL_PRIVATE_KEY=${_PUSH_CHANNEL_PRIVATE_KEY}
    secretEnv: [
      'CHATIZALO_TOKEN', 
      'FRONTEND_TOKEN', 
      'PRIVATE_KEY', 
      'SIGNING_KEY'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: [
      'build',
      '--no-cache',
      '-t',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '-f',
      'Dockerfile',
      '--build-arg',
      'BUN_ENV=${_BUN_ENV}',
      '--build-arg',
      'ALCHEMY_API_KEY=${_ALCHEMY_API_KEY}',
      '--build-arg',
      'INFURA_API_KEY=${_INFURA_API_KEY}',
      '--build-arg',
      'MONGO_URI=${_MONGO_URI}',
      '--build-arg',
      'PRIVATE_KEY=$$PRIVATE_KEY',
      '--build-arg',
      'SIGNING_KEY=$$SIGNING_KEY',
      '--build-arg',
      'PINATA_JWT=${_PINATA_JWT}',
      '--build-arg',
      'ICP_CANISTER_ID=${_ICP_CANISTER_ID}',
      '--build-arg',
      'ICP_MNEMONIC=${_ICP_MNEMONIC}',
      '--build-arg',
      'BOT_API_URL=${_BOT_API_URL}',
      '--build-arg',
      'BOT_DATA_TOKEN=${_BOT_DATA_TOKEN}',
      '--build-arg',
      'NFT_UPLOAD_IMAGE_ICP=${_NFT_UPLOAD_IMAGE_ICP}',
      '--build-arg',
      'NFT_UPLOAD_IMAGE_IPFS=${_NFT_UPLOAD_IMAGE_IPFS}',
      '--build-arg',
      'GCP_BUCKET_BASE_URL=${_GCP_BUCKET_BASE_URL}',
      '--build-arg',
      'ARBITRUM_SEPOLIA_RPC_URL=${_ARBITRUM_SEPOLIA_RPC_URL}',
      '--build-arg',
      'CHATIZALO_TOKEN=$$CHATIZALO_TOKEN',
      '--build-arg',
      'FRONTEND_TOKEN=$$FRONTEND_TOKEN',
      '--build-arg',
      'PUSH_NETWORK=${_PUSH_NETWORK}',
      '--build-arg',
      'PUSH_ENVIRONMENT=${_PUSH_ENVIRONMENT}',
      '--build-arg',
      'PUSH_CHANNEL_ADDRESS=${_PUSH_CHANNEL_ADDRESS}',
      '--build-arg',
      'PUSH_CHANNEL_PRIVATE_KEY=$$PUSH_CHANNEL_PRIVATE_KEY',
      '.'
    ]
    secretEnv: [
      'CHATIZALO_TOKEN', 
      'FRONTEND_TOKEN', 
      'PRIVATE_KEY', 
      'SIGNING_KEY'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: [
      'push',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      '$_SERVICE_NAME',
      '--platform',
      'managed',
      '--region',
      '$_DEPLOY_REGION',
      '--image',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '--labels',
      'managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID',
      '--quiet',
      '--allow-unauthenticated'
    ]

  - name: "bash"
    script: |
      #!/usr/bin/env bash
      echo "CHATIZALO_TOKEN en cloudbuild.yaml 1: $CHATIZALO_TOKEN"
      echo "FRONTEND_TOKEN en cloudbuild.yaml 2: $FRONTEND_TOKEN"
      echo "PRIVATE_KEY en cloudbuild.yaml 3: $PRIVATE_KEY"
      echo "SIGNING_KEY en cloudbuild.yaml 4: $SIGNING_KEY"
    secretEnv: [
      'CHATIZALO_TOKEN', 
      'FRONTEND_TOKEN', 
      'PRIVATE_KEY', 
      'SIGNING_KEY'
    ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_CHATIZALO_TOKEN_SECRET_NAME}/versions/latest
      env: 'CHATIZALO_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/${_FRONTEND_TOKEN_SECRET_NAME}/versions/latest
      env: 'FRONTEND_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/${_PRIVATE_KEY_SECRET_NAME}/versions/latest
      env: 'PRIVATE_KEY'
    - versionName: projects/$PROJECT_ID/secrets/${_SIGNING_KEY_SECRET_NAME}/versions/latest
      env: 'SIGNING_KEY'

images:
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
