/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChatterPayWalletFactory } from './ChatterPayWalletFactory';
export { ChatterPayWalletFactory__factory } from './factories/ChatterPayWalletFactory__factory';
