#!/bin/bash

cd "$(dirname "$0")/.."

export $(grep -v '^#' .env | xargs)

cd scripts

docker build \
  --build-arg BUN_ENV="$BUN_ENV" \
  --build-arg INFURA_API_KEY="$INFURA_API_KEY" \
  --build-arg MONGO_URI="$MONGO_URI" \
  --build-arg SEED_INTERNAL_SALT="$SEED_INTERNAL_SALT" \
  --build-arg SIGNING_KEY="$SIGNING_KEY" \
  --build-arg PINATA_JWT="$PINATA_JWT" \
  --build-arg ICP_CANISTER_ID="$ICP_CANISTER_ID" \
  --build-arg ICP_MNEMONIC="$ICP_MNEMONIC" \
  --build-arg BOT_NOTIFICATIONS_ENABLED="$BOT_NOTIFICATIONS_ENABLED" \
  --build-arg BOT_API_URL="$BOT_API_URL" \
  --build-arg BOT_DATA_TOKEN="$BOT_DATA_TOKEN" \
  --build-arg NFT_UPLOAD_IMAGE_ICP="$NFT_UPLOAD_IMAGE_ICP" \
  --build-arg NFT_UPLOAD_IMAGE_IPFS="$NFT_UPLOAD_IMAGE_IPFS" \
  --build-arg GCP_BUCKET_BASE_URL="$GCP_BUCKET_BASE_URL" \
  --build-arg FRONTEND_TOKEN="$FRONTEND_TOKEN" \
  --build-arg CHATIZALO_TOKEN="$CHATIZALO_TOKEN" \
  --build-arg PUSH_CHANNEL_ADDRESS="$PUSH_CHANNEL_ADDRESS" \
  --build-arg PUSH_CHANNEL_PRIVATE_KEY="$PUSH_CHANNEL_PRIVATE_KEY" \
  --build-arg PUSH_ENABLED="$PUSH_ENABLED" \
  --build-arg PUSH_NETWORK="$PUSH_NETWORK" \
  --build-arg PUSH_ENVIRONMENT="$PUSH_ENVIRONMENT" \
  --build-arg MINOR_LOG_LEVEL="$MINOR_LOG_LEVEL" \
  --build-arg MANTECA_BASE_URL="$MANTECA_BASE_URL" \
  --build-arg MANTECA_API_KEY="$MANTECA_API_KEY" \
  --build-arg GCP_CLOUD_TRACE_ENABLED="$GCP_CLOUD_TRACE_ENABLED" \
  --build-arg CORS_ORIGINS="$CORS_ORIGINS" \
  --build-arg CORS_ORIGINS_CHECK_POSTMAN="$CORS_ORIGINS_CHECK_POSTMAN" \
  --build-arg ABIS_READ_FROM="$ABIS_READ_FROM" \
  --build-arg BLACKLIST_IPS="$BLACKLIST_IPS" \
  --build-arg DEFAULT_CHAIN_ID="$DEFAULT_CHAIN_ID" \
  --build-arg ABIS_VERSION="$ABIS_VERSION" \
  --build-arg SWAP_SLIPPAGE_CONFIG_STABLE="$SLIPPAGE_CONFIG_STABLE" \
  --build-arg SWAP_SLIPPAGE_CONFIG_DEFAULT="$SLIPPAGE_CONFIG_DEFAULT" \
  --build-arg SWAP_SLIPPAGE_CONFIG_EXTRA="$SLIPPAGE_CONFIG_EXTRA" \
  --build-arg SWAP_ZERO_FEE_MODE="$SWAP_ZERO_FEE_MODE" \
  --build-arg SWAP_EXECUTE_SIMPLE="$SWAP_EXECUTE_SIMPLE" \
  --build-arg SWAP_USE_QUOTER="$SWAP_USE_QUOTER" \
  --build-arg CHATIZALO_PHONE_NUMBER="$CHATIZALO_PHONE_NUMBER" \
  --build-arg QUEUE_BUNDLER_INTERVAL="$QUEUE_BUNDLER_INTERVAL" \
  --build-arg QUEUE_GAS_INTERVAL="$QUEUE_GAS_INTERVAL" \
  --build-arg MAX_REQUESTS_PER_MINUTE="$MAX_REQUESTS_PER_MINUTE" \
  --build-arg CHATTERPOINTS_WORDS_SEED="$CHATTERPOINTS_WORDS_SEED" \
  --build-arg CHATTERPOINTS_WORDS_READ_FROM="$CHATTERPOINTS_WORDS_READ_FROM" \
  -t chatterpay-back-app ..
